### ISSUE TITLE
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by bionade24** [Bluewind/filebin#28]
Error came during first setup, trying it to start with docker-compose
Error Message:
```
A Database Error Occurred

SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

Filename: core/MY_Controller.php

Line Number: 16
```

**Comment by Bluewind** [comment]
Can you test the fix I just pushed to the dev branch?

**Comment by bionade24** [comment]
Sadly, the error still remains. I used a random password with letters, like `UksSdsfdT`.

**Comment by Bluewind** [comment]
Have you tried rebuilding the image with `docker-compose build --no-cache`? Maybe you also have to remove the existing containers with `docker-compose rm` since the database is likely not initialized correctly/at all.

**Comment by bionade24** [comment]
Yes, I used the `--no-cache` option to build it. But I'll try to delete the mysql container.

**Comment by bionade24** [comment]
Other docker installations aren't working, too.

**Comment by Bluewind** [comment]
I've just tested this again after having removed all containers and images and it works for me. Can you show me the output of `docker ps --no-trunc | grep -e filebin -e mysql`?

**Comment by bionade24** [comment]
```
6c394b2f570fb12a768ddba7417f471da7c54c3c1f1e13558841447484198b05   docker_filebin                                                            "bash -c ./filebin_starter.sh"                                    23 seconds ago      Up 21 seconds         127.0.0.1:8081->8080/tcp                                                               docker_filebin_1
1d1630052d9abe3aa161c5a1c76c572df371a9e79738007d0475d42dd2400b14   mysql                                                                     "docker-entrypoint.sh mysqld"                                     24 seconds ago      Up 22 seconds         3306/tcp, 33060/tcp                                                                    docker_mysql_1
```

**Comment by Bluewind** [comment]
Somehow your mysqld container is started without the `--default-authentication-plugin=mysql_native_password` option that I have added to the `docker-compose.yml`, but that option is necessary for php to work. Can you check if your `docker-compose.yml` contains `command: --default-authentication-plugin=mysql_native_password` for the mysql service in line 5?

**Comment by bionade24** [comment]
Fixed and works now, thanks.
